### ISSUE TITLE
CMAKE_MODULE_PATH

### ISSUE THREAD

**Issue by MichaelJoker** [ethz-asl/catkin_boost_python_buildtool#3] opened 2020-03-07 09:04 UTC
When I was building the minkindr_python, there are some errors and I couldn't handle them. The errors are as follows:

Errors << minkindr_python:cmake /home/michael/dslam_ws/logs/minkindr_python/build.cmake.021.log
CMake Error at /home/michael/dslam_ws/devel/share/catkin_simple/cmake/catkin_simple-extras.cmake:38 (find_package):

By not providing "Findcatkin_boost_python_buildtool.cmake" in
CMAKE_MODULE_PATH this project has asked CMake to find a package
configuration file provided by "catkin_boost_python_buildtool", but CMake
did not find one.
Could not find a package configuration file provided by
"catkin_boost_python_buildtool" with any of the following names:

catkin_boost_python_buildtoolConfig.cmake
catkin_boost_python_buildtool-config.cmake

Add the installation prefix of "catkin_boost_python_buildtool" to
CMAKE_PREFIX_PATH or set "catkin_boost_python_buildtool_DIR" to a directory
containing one of the above files. If "catkin_boost_python_buildtool"
provides a separate development package or SDK, be sure it has been
installed.
Call Stack (most recent call first):
CMakeLists.txt:5 (catkin_simple)

**Comment by HannesSommer** [comment] 2020-03-07 11:16
Could it be that you don't have this repo cloned into your workspace? Did you follow some instructions that might be missing this information? If so please tell us so we can fix the doc there -- assuming it is ours.

**Comment by HannesSommer** [comment] 2020-03-07 11:20
Closing this because it is a duplicate of https://github.com/ethz-asl/minkindr/issues/70 .

**Closed as completed by HannesSommer** 2020-03-07 11:20 UTC

**Comment by MichaelJoker** [comment] 2020-04-01 01:38
Sorry for the late reply. I have already fixed it as I didn't get the repo in my computer due to some  network problems. Thanks you.

**Comment by ZLIANG-code** [comment] 2022-06-29 08:54
I also encountered the same problem, may I ask if you have solved it？
